"""add_is_deleted_to_product

Revision ID: 03c7b299ddb1
Revises: c5b5dffa9cf4
Create Date: 2026-06-18 15:52:54.425877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '03c7b299ddb1'
down_revision: Union[str, Sequence[str], None] = 'c5b5dffa9cf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.create_index(op.f('ix_products_is_deleted'), 'products', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_is_deleted'), table_name='products')
    op.drop_column('products', 'is_deleted')
    # ### end Alembic commands ###
