"""add_profile_fields_to_seller

Revision ID: 0cd40f0db6e3
Revises: 0ea9e0c080b4
Create Date: 2026-06-15 10:31:16.871959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0cd40f0db6e3'
down_revision: Union[str, Sequence[str], None] = '0ea9e0c080b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sellers', sa.Column('business_email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('sellers', sa.Column('business_address', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('sellers', sa.Column('telegram_username', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sellers', 'telegram_username')
    op.drop_column('sellers', 'business_address')
    op.drop_column('sellers', 'business_email')
    # ### end Alembic commands ###
