"""Initial migration

Revision ID: 74c38fb3a360
Revises: 
Create Date: 2026-06-01 21:50:08.406621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '74c38fb3a360'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_product_images_product_id'), table_name='product_images')
    op.drop_table('product_images')
    op.drop_index(op.f('idx_status_logs_changed_at'), table_name='order_status_logs')
    op.drop_index(op.f('idx_status_logs_order_id'), table_name='order_status_logs')
    op.drop_table('order_status_logs')
    op.drop_index(op.f('idx_orders_buyer_phone'), table_name='orders')
    op.drop_index(op.f('idx_orders_created_at'), table_name='orders')
    op.drop_index(op.f('idx_orders_order_id'), table_name='orders')
    op.drop_index(op.f('idx_orders_seller_id'), table_name='orders')
    op.drop_index(op.f('idx_orders_status'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('idx_product_attributes_product_id'), table_name='product_attributes')
    op.drop_index(op.f('idx_product_attributes_unique'), table_name='product_attributes')
    op.drop_table('product_attributes')
    op.drop_index(op.f('idx_products_in_stock'), table_name='products')
    op.drop_index(op.f('idx_products_seller_id'), table_name='products')
    op.drop_table('products')
    op.alter_column('otp_codes', 'used',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('otp_codes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_otp_expires_at'), table_name='otp_codes')
    op.drop_index(op.f('idx_otp_phone_code'), table_name='otp_codes')
    op.create_index(op.f('ix_otp_codes_expires_at'), 'otp_codes', ['expires_at'], unique=False)
    op.create_index(op.f('ix_otp_codes_phone'), 'otp_codes', ['phone'], unique=False)
    op.add_column('sellers', sa.Column('store_prefix', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False))
    op.alter_column('sellers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('sellers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(op.f('sellers_phone_key'), 'sellers', type_='unique')
    op.drop_constraint(op.f('sellers_store_name_key'), 'sellers', type_='unique')
    op.create_index(op.f('ix_sellers_phone'), 'sellers', ['phone'], unique=True)
    op.create_index(op.f('ix_sellers_store_name'), 'sellers', ['store_name'], unique=True)
    op.create_unique_constraint(None, 'sellers', ['store_prefix'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sellers', type_='unique')
    op.drop_index(op.f('ix_sellers_store_name'), table_name='sellers')
    op.drop_index(op.f('ix_sellers_phone'), table_name='sellers')
    op.create_unique_constraint(op.f('sellers_store_name_key'), 'sellers', ['store_name'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('sellers_phone_key'), 'sellers', ['phone'], postgresql_nulls_not_distinct=False)
    op.alter_column('sellers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('sellers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_column('sellers', 'store_prefix')
    op.drop_index(op.f('ix_otp_codes_phone'), table_name='otp_codes')
    op.drop_index(op.f('ix_otp_codes_expires_at'), table_name='otp_codes')
    op.create_index(op.f('idx_otp_phone_code'), 'otp_codes', ['phone', 'code'], unique=False)
    op.create_index(op.f('idx_otp_expires_at'), 'otp_codes', ['expires_at'], unique=False)
    op.alter_column('otp_codes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('otp_codes', 'used',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.create_table('products',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('seller_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('in_stock', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.CheckConstraint('price >= 0::numeric', name=op.f('products_price_check')),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], name=op.f('products_seller_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('products_pkey'))
    )
    op.create_index(op.f('idx_products_seller_id'), 'products', ['seller_id'], unique=False)
    op.create_index(op.f('idx_products_in_stock'), 'products', ['in_stock'], unique=False)
    op.create_table('product_attributes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('attribute_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('attribute_value', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('extra_price', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0.00'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('product_attributes_product_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('product_attributes_pkey'))
    )
    op.create_index(op.f('idx_product_attributes_unique'), 'product_attributes', ['product_id', 'attribute_type', 'attribute_value'], unique=True)
    op.create_index(op.f('idx_product_attributes_product_id'), 'product_attributes', ['product_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('seller_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('buyer_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('buyer_phone', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('delivery_address', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('product_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('attributes_selected', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('subtotal', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('total_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=True),
    sa.Column('status_updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.CheckConstraint("status::text = ANY (ARRAY['pending'::character varying, 'shipped'::character varying, 'completed'::character varying, 'cancelled'::character varying]::text[])", name=op.f('valid_status')),
    sa.CheckConstraint('quantity >= 1 AND quantity <= 10', name=op.f('orders_quantity_check')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('orders_product_id_fkey')),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], name=op.f('orders_seller_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('orders_pkey')),
    sa.UniqueConstraint('order_id', name=op.f('orders_order_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('idx_orders_seller_id'), 'orders', ['seller_id'], unique=False)
    op.create_index(op.f('idx_orders_order_id'), 'orders', ['order_id'], unique=False)
    op.create_index(op.f('idx_orders_created_at'), 'orders', ['created_at'], unique=False)
    op.create_index(op.f('idx_orders_buyer_phone'), 'orders', ['buyer_phone'], unique=False)
    op.create_table('order_status_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('old_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('new_status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('changed_by', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('changed_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('order_status_logs_order_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('order_status_logs_pkey'))
    )
    op.create_index(op.f('idx_status_logs_order_id'), 'order_status_logs', ['order_id'], unique=False)
    op.create_index(op.f('idx_status_logs_changed_at'), 'order_status_logs', ['changed_at'], unique=False)
    op.create_table('product_images',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('image_url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('image_tag', sa.VARCHAR(length=20), server_default=sa.text("'gallery'::character varying"), autoincrement=False, nullable=True),
    sa.Column('display_order', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('product_images_product_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('product_images_pkey'))
    )
    op.create_index(op.f('idx_product_images_product_id'), 'product_images', ['product_id'], unique=False)
    # ### end Alembic commands ###
