"""Add product and order models

Revision ID: ac683a6bc129
Revises: 74c38fb3a360
Create Date: 2026-06-01 21:57:43.709706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ac683a6bc129'
down_revision: Union[str, Sequence[str], None] = '74c38fb3a360'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('price', sa.Numeric(scale=2), nullable=False),
    sa.Column('in_stock', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_in_stock'), 'products', ['in_stock'], unique=False)
    op.create_index(op.f('ix_products_seller_id'), 'products', ['seller_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('buyer_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('buyer_phone', sqlmodel.sql.sqltypes.AutoString(length=15), nullable=False),
    sa.Column('delivery_address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('product_price', sa.Numeric(scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('attributes_selected', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('subtotal', sa.Numeric(scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(scale=2), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('status_updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_buyer_phone'), 'orders', ['buyer_phone'], unique=False)
    op.create_index(op.f('ix_orders_order_id'), 'orders', ['order_id'], unique=True)
    op.create_index(op.f('ix_orders_seller_id'), 'orders', ['seller_id'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_table('product_attributes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('attribute_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('attribute_value', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('extra_price', sa.Numeric(scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_attributes_product_id'), 'product_attributes', ['product_id'], unique=False)
    op.create_table('product_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('image_tag', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_images_product_id'), 'product_images', ['product_id'], unique=False)
    op.create_table('order_status_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('old_status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('new_status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('changed_by', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_status_logs_changed_at'), 'order_status_logs', ['changed_at'], unique=False)
    op.create_index(op.f('ix_order_status_logs_order_id'), 'order_status_logs', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_status_logs_order_id'), table_name='order_status_logs')
    op.drop_index(op.f('ix_order_status_logs_changed_at'), table_name='order_status_logs')
    op.drop_table('order_status_logs')
    op.drop_index(op.f('ix_product_images_product_id'), table_name='product_images')
    op.drop_table('product_images')
    op.drop_index(op.f('ix_product_attributes_product_id'), table_name='product_attributes')
    op.drop_table('product_attributes')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_seller_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_buyer_phone'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_products_seller_id'), table_name='products')
    op.drop_index(op.f('ix_products_in_stock'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
