"""add image processing fields

Revision ID: b5b9475effb4
Revises: 5f3a9c21b7d0
Create Date: 2026-09-30 18:22:40.767881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b5b9475effb4'
down_revision: Union[str, Sequence[str], None] = '5f3a9c21b7d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_created_at'), table_name='orders')
    op.drop_index(op.f('ix_products_active_created'), table_name='products')
    op.drop_index(op.f('ix_products_active_price'), table_name='products')
    op.drop_index(op.f('ix_sellers_updated_at'), table_name='sellers')
    
    # Add new image processing fields
    op.add_column('product_images', sa.Column('object_name', sa.String(), nullable=True, server_default=''))
    op.add_column('product_images', sa.Column('processed_urls', sa.JSON(), nullable=True))
    op.add_column('product_images', sa.Column('processing_status', sa.String(length=20), nullable=False, server_default='pending'))
    op.add_column('product_images', sa.Column('processing_error', sa.Text(), nullable=True))
    op.add_column('product_images', sa.Column('processed_at', sa.DateTime(), nullable=True))
    op.add_column('product_images', sa.Column('image_url', sa.String(), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_sellers_updated_at'), 'sellers', ['updated_at'], unique=False)
    op.create_index(op.f('ix_products_active_price'), 'products', ['in_stock', 'is_deleted', 'price'], unique=False)
    op.create_index(op.f('ix_products_active_created'), 'products', ['in_stock', 'is_deleted', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_orders_created_at'), 'orders', ['created_at'], unique=False)
    
    # Remove image processing fields
    op.drop_column('product_images', 'image_url')
    op.drop_column('product_images', 'processed_at')
    op.drop_column('product_images', 'processing_error')
    op.drop_column('product_images', 'processing_status')
    op.drop_column('product_images', 'processed_urls')
    op.drop_column('product_images', 'object_name')
    # ### end Alembic commands ###
