"""add attempts column to otp_codes

Revision ID: bf9fa547aa63
Revises: ac683a6bc129
Create Date: 2026-06-05 11:31:32.096877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bf9fa547aa63'
down_revision: Union[str, Sequence[str], None] = 'ac683a6bc129'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otp_codes', sa.Column('attempts', sa.Integer(), nullable=True))
    op.execute("UPDATE otp_codes SET attempts = 0 WHERE attempts IS NULL")
    op.alter_column('otp_codes', 'attempts', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('otp_codes', 'attempts')
    # ### end Alembic commands ###
