"""add_context_to_order_status_log

Revision ID: c5b5dffa9cf4
Revises: c9c3a415f1c9
Create Date: 2026-06-15 11:47:42.679886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c5b5dffa9cf4'
down_revision: Union[str, Sequence[str], None] = 'c9c3a415f1c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_status_logs', sa.Column('context', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_status_logs', 'context')
    # ### end Alembic commands ###
