"""add_business_contact_number_to_seller

Revision ID: c9c3a415f1c9
Revises: 0cd40f0db6e3
Create Date: 2026-06-15 11:14:21.255792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c9c3a415f1c9'
down_revision: Union[str, Sequence[str], None] = '0cd40f0db6e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sellers', sa.Column('business_contact_number', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sellers', 'business_contact_number')
    # ### end Alembic commands ###
