"""Add featured_image to seller

Revision ID: f77d2dcc5905
Revises: 7ef2f0eae81a
Create Date: 2026-06-24 19:51:38.046868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f77d2dcc5905'
down_revision: Union[str, Sequence[str], None] = '7ef2f0eae81a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sellers', sa.Column('featured_image', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sellers', 'featured_image')
    # ### end Alembic commands ###
